-- 扩展 RepositoryStatus 枚举，新增 CLONING 和 SYNCING 中间态。
-- MySQL ALTER ENUM 需要重新声明完整列表。
ALTER TABLE codeRepository MODIFY COLUMN status ENUM('CREATED','CLONING','SYNCING','INDEXING','READY','FAILED') NOT NULL DEFAULT 'CREATED';
